# Hyperparameter Optimization

In [1]:
import warnings
import joblib
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import roc_curve, confusion_matrix, roc_auc_score
from catboost import CatBoostClassifier
from skopt.space import Integer, Real

import sys 
sys.path.append('..')  

from module.dataload import DPN_data
import ymlconfig

%matplotlib inline
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')
np.set_printoptions(precision=3)  # decimal places for outputs from numpy
pd.set_option("display.precision", 3)  # decimal places for outputs from pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Load / Reload Selection Utility Functions

In [2]:
from utils2 import optimization as hpo

----

## Read Config File

In [3]:
config_path = Path(r'experiments\binary')
config_file = config_path / "optimization_config_dev.yml"
#config_file = config_path / "optimization_config_final.yml"
config_dict = ymlconfig.load_config(config_file)
config = ymlconfig.dict_to_namespace(config_dict)
config_dict

{'experiment': {'summary': 'binary classification - hyperparameter optimization(final experiment)',
  'classification_type': 'binary',
  'stage': 'hyperparameter_optimization',
  'tag': 'development',
  'verbosity': 1,
  'random_seed': 42},
 'data': {'dataset_path': '../dataset/Sudoscan Working File with Stats.xlsx'},
 'model': {'name': 'catboost'},
 'param_space': {'iterations': {'min': 100, 'max': 500},
  'depth': {'min': 4, 'max': 10},
  'learning_rate': {'min': 0.01, 'max': 0.1},
  'l2_leaf_reg': {'min': 1, 'max': 9}},
 'optimization': {'scoring': 'roc_auc',
  'k_splits_outer': 3,
  'n_repeats_outer': 2,
  'k_splits_inner': 3,
  'n_iter': 5},
 'evaluation': {'confidence': 0.95},
 'final_training': {'k_splits_inner': 3, 'n_iter': 5}}

## Data Loading

In [4]:
D = DPN_data(config.data.dataset_path)
D.load(classification=config.experiment.classification_type)

dfdpn = D.df
data_cols = dfdpn.drop(D.non_data_cols, axis=1, errors="ignore").columns
X = dfdpn[data_cols]
y = dfdpn['Confirmed_Binary_DPN']
X.shape, y.shape

((190, 40), (190,))

## Optuna Bayes Search Optimization

In [5]:
config.param_space

namespace(iterations=namespace(min=100, max=500),
          depth=namespace(min=4, max=10),
          learning_rate=namespace(min=0.01, max=0.1),
          l2_leaf_reg=namespace(min=1, max=9))

In [6]:
hpo.model_class[config.model.name]

catboost.core.CatBoostClassifier

In [7]:
config.optimization

namespace(scoring='roc_auc',
          k_splits_outer=3,
          n_repeats_outer=2,
          k_splits_inner=3,
          n_iter=5)

In [8]:
def param_space_fn(trial):
    return  {
        "iterations": trial.suggest_int(
            "iterations", 
            config.param_space.iterations.min, 
            config.param_space.iterations.max),
        "depth": trial.suggest_int(
            "depth", 
            config.param_space.depth.min, 
            config.param_space.depth.max),
        "learning_rate": trial.suggest_float(
            "learning_rate", 
            config.param_space.learning_rate.min, 
            config.param_space.learning_rate.max, 
            log=True),
        "l2_leaf_reg": trial.suggest_int(
            "l2_leaf_reg", 
            config.param_space.l2_leaf_reg.min, 
            config.param_space.l2_leaf_reg.max),
    }

In [9]:
opt_results = hpo.nested_cv_youden_optuna(
    X=X.values,
    y=y.values,
    model_class=hpo.model_class[config.model.name],   # class, not an instance
    param_space_fn=param_space_fn,
    n_splits_outer=config.optimization.k_splits_outer,
    n_repeats_outer=config.optimization.n_repeats_outer,
    n_splits_inner=config.optimization.k_splits_inner,
    n_iter=config.optimization.n_iter,   # Optuna trials per outer fold
    random_state=config.experiment.random_seed,
)

In [10]:
opt_results

{'roc_auc_mean': 0.9692212825933756,
 'roc_auc_std': 0.018776054590824542,
 'youden_mean': 0.7956483439041578,
 'youden_std': 0.08021401914153416,
 'sensitivity_mean': 0.9039816772374912,
 'specificity_mean': 0.8916666666666666,
 'threshold_mean': 0.6488591221384802,
 'threshold_std': 0.14354802298703395,
 'folds': [{'fold': 0,
   'roc_auc': 0.9840909090909091,
   'youden': 0.9090909090909092,
   'sensitivity': 0.9090909090909091,
   'specificity': 1.0,
   'threshold': 0.7137815889585889,
   'best_params': {'iterations': 433,
    'depth': 5,
    'learning_rate': 0.015199348301309814,
    'l2_leaf_reg': 2}},
  {'fold': 1,
   'roc_auc': 0.9755813953488373,
   'youden': 0.6499999999999999,
   'sensitivity': 1.0,
   'specificity': 0.65,
   'threshold': 0.3794176963815851,
   'best_params': {'iterations': 231,
    'depth': 10,
    'learning_rate': 0.04635431984752397,
    'l2_leaf_reg': 5}},
  {'fold': 2,
   'roc_auc': 0.9348837209302325,
   'youden': 0.8069767441860465,
   'sensitivity': 0.9069767441860465,
   'specificity': 0.9,
   'threshold': 0.6339991006349044,
   'best_params': {'iterations': 244,
    'depth': 8,
    'learning_rate': 0.024761648314181258,
    'l2_leaf_reg': 4}},
  {'fold': 3,
   'roc_auc': 0.9568181818181818,
   'youden': 0.7636363636363637,
   'sensitivity': 0.8636363636363636,
   'specificity': 0.9,
   'threshold': 0.7714033672672544,
   'best_params': {'iterations': 496,
    'depth': 7,
    'learning_rate': 0.019118213268168986,
    'l2_leaf_reg': 1}},
  {'fold': 4,
   'roc_auc': 0.9720930232558139,
   'youden': 0.8534883720930233,
   'sensitivity': 0.9534883720930233,
   'specificity': 0.9,
   'threshold': 0.5813105345007075,
   'best_params': {'iterations': 141,
    'depth': 9,
    'learning_rate': 0.024821724395582237,
    'l2_leaf_reg': 6}},
  {'fold': 5,
   'roc_auc': 0.991860465116279,
   'youden': 0.7906976744186047,
   'sensitivity': 0.7906976744186046,
   'specificity': 1.0,
   'threshold': 0.8132424450878413,
   'best_params': {'iterations': 383,
    'depth': 9,
    'learning_rate': 0.044214208459664416,
    'l2_leaf_reg': 4}}]}

### Calculate Confidence Interval

In [11]:
opt_ci  = hpo.mean_confidence_interval(opt_results, config)
opt_ci

youden 95.0% CI: {'mean': 0.7956483439041578, 'std': 0.08787005542393887, 'ci_lower': 0.7253389480563618, 'ci_upper': 0.8659577397519539, 'n_folds': 6}
roc_auc 95.0% CI: {'mean': 0.9692212825933756, 'std': 0.020568137280686065, 'ci_lower': 0.9527636475214215, 'ci_upper': 0.9856789176653297, 'n_folds': 6}

{'youden': {'mean': 0.7956483439041578,
  'std': 0.08787005542393887,
  'ci_lower': 0.7253389480563618,
  'ci_upper': 0.8659577397519539,
  'n_folds': 6},
 'roc_auc': {'mean': 0.9692212825933756,
  'std': 0.020568137280686065,
  'ci_lower': 0.9527636475214215,
  'ci_upper': 0.9856789176653297,
  'n_folds': 6}}

### Optimization Summary

In [12]:
opt_results_summary = {
    'youden': f'{opt_results["youden_mean"]:.3f} +/ {opt_results["youden_std"]:.3f}',
    'youden ci': f'{opt_ci["youden"]["ci_lower"]:.3f} - {opt_ci["youden"]["ci_upper"]:.3f}', 
    'roc_auc': f'{opt_results["roc_auc_mean"]:.3f} +/ {opt_results["roc_auc_std"]:.3f}',
    'roc_auc ci': f'{opt_ci["roc_auc"]["ci_lower"]:.3f} - {opt_ci["roc_auc"]["ci_upper"]:.3f}', 
    'threshold': f'{opt_results["threshold_mean"]:.3f} +/ {opt_results["threshold_std"]:.3f}',
    'specificity mean': f'{opt_results["specificity_mean"]:.3f}',
    'sensitivity mean': f'{opt_results["sensitivity_mean"]:.3f}',
}

opt_results_df = pd.DataFrame(opt_results_summary, index=['value']).T
opt_results_df

                           value
youden            0.796 +/ 0.080
youden ci          0.725 - 0.866
roc_auc           0.969 +/ 0.019
roc_auc ci         0.953 - 0.986
threshold         0.649 +/ 0.144
specificity mean           0.892
sensitivity mean           0.904

 -----

### Train final model on ALL data

In [13]:
catboost_model = CatBoostClassifier(
    verbose=0,
    loss_function="Logloss",
    eval_metric="AUC",
    random_state=config.experiment.random_seed, 
    thread_count=-1
)

In [14]:
param_space = {
    'iterations': Integer(
        config.param_space.iterations.min, 
        config.param_space.iterations.max),
    'depth': Integer(
        config.param_space.depth.min, 
        config.param_space.depth.max),
    'learning_rate': Real(
        config.param_space.learning_rate.min, 
        config.param_space.learning_rate.max, 
        prior='log-uniform'),  # log-uniform better for LR
    'l2_leaf_reg': Real(
        config.param_space.l2_leaf_reg.min, 
        config.param_space.l2_leaf_reg.max, 
        prior='uniform'),
}

In [15]:
final_model, final_threshold, best_params = hpo.train_final_model(
    X=X.values, 
    y=y.values, 
    model=catboost_model, 
    param_space=param_space,
    n_splits_inner=config.final_training.k_splits_inner,
    n_iter=config.final_training.n_iter, 
    random_state=config.experiment.random_seed, 
    n_jobs=1
)

0:	learn: 0.6766401	total: 4.53ms	remaining: 1.76s
1:	learn: 0.6610091	total: 7.34ms	remaining: 1.43s
2:	learn: 0.6448277	total: 9.44ms	remaining: 1.22s
3:	learn: 0.6300781	total: 13.3ms	remaining: 1.29s
4:	learn: 0.6166119	total: 17ms	remaining: 1.31s
5:	learn: 0.6024873	total: 19.4ms	remaining: 1.25s
6:	learn: 0.5864141	total: 21.9ms	remaining: 1.2s
7:	learn: 0.5755168	total: 24ms	remaining: 1.15s
8:	learn: 0.5622360	total: 27ms	remaining: 1.15s
9:	learn: 0.5492061	total: 29.3ms	remaining: 1.12s
10:	learn: 0.5376998	total: 31.5ms	remaining: 1.09s
11:	learn: 0.5275073	total: 33.5ms	remaining: 1.06s
12:	learn: 0.5180197	total: 35.4ms	remaining: 1.03s
13:	learn: 0.5056234	total: 37.3ms	remaining: 1s
14:	learn: 0.4967230	total: 39ms	remaining: 978ms
15:	learn: 0.4862811	total: 41.5ms	remaining: 973ms
16:	learn: 0.4784654	total: 43.8ms	remaining: 964ms
17:	learn: 0.4701739	total: 46.1ms	remaining: 956ms
18:	learn: 0.4614774	total: 48.2ms	remaining: 943ms
19:	learn: 0.4521201	total: 50.5ms	remaining: 937ms
20:	learn: 0.4435414	total: 52.3ms	remaining: 921ms
21:	learn: 0.4351568	total: 54.1ms	remaining: 908ms
22:	learn: 0.4265961	total: 56.4ms	remaining: 903ms
23:	learn: 0.4187295	total: 59.1ms	remaining: 903ms
24:	learn: 0.4098987	total: 60.9ms	remaining: 891ms
25:	learn: 0.4044682	total: 62.7ms	remaining: 880ms
26:	learn: 0.3974931	total: 64.6ms	remaining: 871ms
27:	learn: 0.3907326	total: 66.6ms	remaining: 863ms
28:	learn: 0.3830735	total: 68.8ms	remaining: 858ms
29:	learn: 0.3755421	total: 70.7ms	remaining: 851ms
30:	learn: 0.3688157	total: 73.8ms	remaining: 857ms
31:	learn: 0.3636522	total: 76ms	remaining: 853ms
32:	learn: 0.3588994	total: 78.1ms	remaining: 847ms
33:	learn: 0.3545268	total: 80.3ms	remaining: 843ms
34:	learn: 0.3501474	total: 82.2ms	remaining: 836ms
35:	learn: 0.3442527	total: 84.1ms	remaining: 830ms
36:	learn: 0.3396203	total: 86.4ms	remaining: 827ms
37:	learn: 0.3343102	total: 89.5ms	remaining: 831ms
38:	learn: 0.3299080	total: 91.6ms	remaining: 827ms
39:	learn: 0.3245223	total: 93.4ms	remaining: 820ms
40:	learn: 0.3191041	total: 95.5ms	remaining: 815ms
41:	learn: 0.3139493	total: 97.6ms	remaining: 811ms
42:	learn: 0.3099096	total: 99.4ms	remaining: 804ms
43:	learn: 0.3072910	total: 101ms	remaining: 798ms
44:	learn: 0.3036861	total: 103ms	remaining: 794ms
45:	learn: 0.3002208	total: 105ms	remaining: 790ms
46:	learn: 0.2941706	total: 108ms	remaining: 787ms
47:	learn: 0.2904302	total: 109ms	remaining: 782ms
48:	learn: 0.2848121	total: 112ms	remaining: 778ms
49:	learn: 0.2819011	total: 113ms	remaining: 773ms
50:	learn: 0.2775032	total: 115ms	remaining: 770ms
51:	learn: 0.2733263	total: 117ms	remaining: 766ms
52:	learn: 0.2701575	total: 120ms	remaining: 766ms
53:	learn: 0.2667518	total: 123ms	remaining: 765ms
54:	learn: 0.2644008	total: 125ms	remaining: 761ms
55:	learn: 0.2612965	total: 126ms	remaining: 756ms
56:	learn: 0.2585257	total: 128ms	remaining: 752ms
57:	learn: 0.2558010	total: 130ms	remaining: 747ms
58:	learn: 0.2530177	total: 132ms	remaining: 744ms
59:	learn: 0.2506158	total: 137ms	remaining: 757ms
60:	learn: 0.2478965	total: 140ms	remaining: 757ms
61:	learn: 0.2446107	total: 142ms	remaining: 753ms
62:	learn: 0.2417817	total: 144ms	remaining: 751ms
63:	learn: 0.2386144	total: 146ms	remaining: 747ms
64:	learn: 0.2360532	total: 148ms	remaining: 742ms
65:	learn: 0.2333382	total: 151ms	remaining: 742ms
66:	learn: 0.2305010	total: 154ms	remaining: 745ms
67:	learn: 0.2274592	total: 156ms	remaining: 743ms
68:	learn: 0.2247828	total: 159ms	remaining: 740ms
69:	learn: 0.2226117	total: 161ms	remaining: 737ms
70:	learn: 0.2195552	total: 163ms	remaining: 735ms
71:	learn: 0.2165140	total: 165ms	remaining: 732ms
72:	learn: 0.2146115	total: 168ms	remaining: 731ms
73:	learn: 0.2131191	total: 170ms	remaining: 728ms
74:	learn: 0.2116647	total: 172ms	remaining: 726ms
75:	learn: 0.2095045	total: 174ms	remaining: 723ms
76:	learn: 0.2069272	total: 176ms	remaining: 719ms
77:	learn: 0.2044681	total: 178ms	remaining: 714ms
78:	learn: 0.2026826	total: 180ms	remaining: 710ms
79:	learn: 0.2007701	total: 182ms	remaining: 709ms
80:	learn: 0.1985101	total: 185ms	remaining: 710ms
81:	learn: 0.1971058	total: 187ms	remaining: 706ms
82:	learn: 0.1950164	total: 189ms	remaining: 702ms
83:	learn: 0.1929980	total: 192ms	remaining: 701ms
84:	learn: 0.1909158	total: 194ms	remaining: 698ms
85:	learn: 0.1898128	total: 196ms	remaining: 694ms
86:	learn: 0.1883846	total: 199ms	remaining: 694ms
87:	learn: 0.1856780	total: 201ms	remaining: 692ms
88:	learn: 0.1835661	total: 203ms	remaining: 689ms
89:	learn: 0.1815376	total: 205ms	remaining: 686ms
90:	learn: 0.1798420	total: 207ms	remaining: 683ms
91:	learn: 0.1784194	total: 209ms	remaining: 680ms
92:	learn: 0.1763573	total: 211ms	remaining: 677ms
93:	learn: 0.1748692	total: 214ms	remaining: 676ms
94:	learn: 0.1730827	total: 216ms	remaining: 673ms
95:	learn: 0.1715698	total: 219ms	remaining: 672ms
96:	learn: 0.1692310	total: 222ms	remaining: 673ms
97:	learn: 0.1681328	total: 224ms	remaining: 670ms
98:	learn: 0.1668238	total: 226ms	remaining: 666ms
99:	learn: 0.1655677	total: 228ms	remaining: 664ms
100:	learn: 0.1638824	total: 231ms	remaining: 663ms
101:	learn: 0.1623766	total: 233ms	remaining: 660ms
102:	learn: 0.1611605	total: 235ms	remaining: 657ms
103:	learn: 0.1599799	total: 237ms	remaining: 654ms
104:	learn: 0.1585682	total: 239ms	remaining: 652ms
105:	learn: 0.1572141	total: 242ms	remaining: 650ms
106:	learn: 0.1558839	total: 244ms	remaining: 647ms
107:	learn: 0.1545571	total: 247ms	remaining: 647ms
108:	learn: 0.1533120	total: 249ms	remaining: 644ms
109:	learn: 0.1521377	total: 251ms	remaining: 641ms
110:	learn: 0.1511113	total: 253ms	remaining: 638ms
111:	learn: 0.1498688	total: 255ms	remaining: 635ms
112:	learn: 0.1485475	total: 257ms	remaining: 633ms
113:	learn: 0.1472858	total: 259ms	remaining: 630ms
114:	learn: 0.1462208	total: 263ms	remaining: 630ms
115:	learn: 0.1452877	total: 265ms	remaining: 629ms
116:	learn: 0.1442799	total: 267ms	remaining: 626ms
117:	learn: 0.1425792	total: 269ms	remaining: 623ms
118:	learn: 0.1412020	total: 271ms	remaining: 620ms
119:	learn: 0.1396373	total: 273ms	remaining: 617ms
120:	learn: 0.1389620	total: 275ms	remaining: 614ms
121:	learn: 0.1378646	total: 279ms	remaining: 615ms
122:	learn: 0.1365554	total: 281ms	remaining: 612ms
123:	learn: 0.1356580	total: 283ms	remaining: 609ms
124:	learn: 0.1343183	total: 285ms	remaining: 607ms
125:	learn: 0.1333077	total: 287ms	remaining: 604ms
126:	learn: 0.1323895	total: 289ms	remaining: 601ms
127:	learn: 0.1311018	total: 292ms	remaining: 599ms
128:	learn: 0.1300187	total: 295ms	remaining: 599ms
129:	learn: 0.1288573	total: 297ms	remaining: 596ms
130:	learn: 0.1276886	total: 298ms	remaining: 592ms
131:	learn: 0.1269867	total: 301ms	remaining: 590ms
132:	learn: 0.1260731	total: 303ms	remaining: 587ms
133:	learn: 0.1250262	total: 305ms	remaining: 585ms
134:	learn: 0.1241198	total: 307ms	remaining: 582ms
135:	learn: 0.1230303	total: 310ms	remaining: 581ms
136:	learn: 0.1223445	total: 312ms	remaining: 579ms
137:	learn: 0.1213199	total: 314ms	remaining: 576ms
138:	learn: 0.1205021	total: 316ms	remaining: 573ms
139:	learn: 0.1196102	total: 318ms	remaining: 570ms
140:	learn: 0.1190438	total: 320ms	remaining: 567ms
141:	learn: 0.1185247	total: 322ms	remaining: 565ms
142:	learn: 0.1179600	total: 324ms	remaining: 562ms
143:	learn: 0.1170599	total: 327ms	remaining: 561ms
144:	learn: 0.1163889	total: 329ms	remaining: 558ms
145:	learn: 0.1156227	total: 331ms	remaining: 555ms
146:	learn: 0.1148048	total: 333ms	remaining: 553ms
147:	learn: 0.1140721	total: 335ms	remaining: 551ms
148:	learn: 0.1131779	total: 337ms	remaining: 548ms
149:	learn: 0.1125654	total: 339ms	remaining: 545ms
150:	learn: 0.1114164	total: 342ms	remaining: 544ms
151:	learn: 0.1107376	total: 344ms	remaining: 541ms
152:	learn: 0.1100761	total: 346ms	remaining: 538ms
153:	learn: 0.1093537	total: 348ms	remaining: 536ms
154:	learn: 0.1085230	total: 350ms	remaining: 533ms
155:	learn: 0.1076826	total: 352ms	remaining: 530ms
156:	learn: 0.1069278	total: 354ms	remaining: 528ms
157:	learn: 0.1061767	total: 357ms	remaining: 527ms
158:	learn: 0.1053887	total: 360ms	remaining: 525ms
159:	learn: 0.1047711	total: 362ms	remaining: 522ms
160:	learn: 0.1039569	total: 364ms	remaining: 520ms
161:	learn: 0.1033070	total: 366ms	remaining: 517ms
162:	learn: 0.1026662	total: 368ms	remaining: 514ms
163:	learn: 0.1021033	total: 370ms	remaining: 512ms
164:	learn: 0.1014377	total: 373ms	remaining: 511ms
165:	learn: 0.1007744	total: 375ms	remaining: 508ms
166:	learn: 0.1000838	total: 377ms	remaining: 506ms
167:	learn: 0.0995095	total: 379ms	remaining: 503ms
168:	learn: 0.0987378	total: 381ms	remaining: 501ms
169:	learn: 0.0981645	total: 383ms	remaining: 498ms
170:	learn: 0.0972837	total: 385ms	remaining: 495ms
171:	learn: 0.0966634	total: 388ms	remaining: 494ms
172:	learn: 0.0958588	total: 390ms	remaining: 492ms
173:	learn: 0.0953617	total: 393ms	remaining: 490ms
174:	learn: 0.0948170	total: 395ms	remaining: 487ms
175:	learn: 0.0942894	total: 397ms	remaining: 484ms
176:	learn: 0.0936863	total: 399ms	remaining: 482ms
177:	learn: 0.0930258	total: 401ms	remaining: 480ms
178:	learn: 0.0923432	total: 404ms	remaining: 479ms
179:	learn: 0.0917805	total: 406ms	remaining: 476ms
180:	learn: 0.0912958	total: 409ms	remaining: 474ms
181:	learn: 0.0910456	total: 411ms	remaining: 472ms
182:	learn: 0.0902430	total: 413ms	remaining: 469ms
183:	learn: 0.0897833	total: 415ms	remaining: 467ms
184:	learn: 0.0891282	total: 417ms	remaining: 464ms
185:	learn: 0.0886046	total: 422ms	remaining: 465ms
186:	learn: 0.0879470	total: 425ms	remaining: 464ms
187:	learn: 0.0875696	total: 428ms	remaining: 462ms
188:	learn: 0.0869514	total: 430ms	remaining: 459ms
189:	learn: 0.0860487	total: 432ms	remaining: 457ms
190:	learn: 0.0853135	total: 435ms	remaining: 456ms
191:	learn: 0.0847221	total: 438ms	remaining: 454ms
192:	learn: 0.0841288	total: 442ms	remaining: 453ms
193:	learn: 0.0835897	total: 445ms	remaining: 452ms
194:	learn: 0.0831938	total: 448ms	remaining: 450ms
195:	learn: 0.0827519	total: 452ms	remaining: 450ms
196:	learn: 0.0821953	total: 456ms	remaining: 449ms
197:	learn: 0.0817488	total: 459ms	remaining: 447ms
198:	learn: 0.0812458	total: 461ms	remaining: 445ms
199:	learn: 0.0808531	total: 463ms	remaining: 442ms
200:	learn: 0.0803629	total: 465ms	remaining: 440ms
201:	learn: 0.0799686	total: 469ms	remaining: 439ms
202:	learn: 0.0794410	total: 471ms	remaining: 437ms
203:	learn: 0.0789134	total: 474ms	remaining: 435ms
204:	learn: 0.0785298	total: 477ms	remaining: 432ms
205:	learn: 0.0779762	total: 478ms	remaining: 430ms
206:	learn: 0.0775923	total: 481ms	remaining: 427ms
207:	learn: 0.0772250	total: 483ms	remaining: 425ms
208:	learn: 0.0767164	total: 485ms	remaining: 423ms
209:	learn: 0.0761664	total: 487ms	remaining: 420ms
210:	learn: 0.0753964	total: 490ms	remaining: 418ms
211:	learn: 0.0749057	total: 491ms	remaining: 415ms
212:	learn: 0.0744915	total: 494ms	remaining: 413ms
213:	learn: 0.0740852	total: 496ms	remaining: 410ms
214:	learn: 0.0735679	total: 499ms	remaining: 409ms
215:	learn: 0.0731224	total: 502ms	remaining: 407ms
216:	learn: 0.0727967	total: 504ms	remaining: 404ms
217:	learn: 0.0723872	total: 507ms	remaining: 402ms
218:	learn: 0.0719819	total: 508ms	remaining: 399ms
219:	learn: 0.0715289	total: 510ms	remaining: 397ms
220:	learn: 0.0711513	total: 513ms	remaining: 394ms
221:	learn: 0.0706603	total: 516ms	remaining: 393ms
222:	learn: 0.0702677	total: 518ms	remaining: 390ms
223:	learn: 0.0697933	total: 520ms	remaining: 387ms
224:	learn: 0.0694182	total: 522ms	remaining: 385ms
225:	learn: 0.0690985	total: 524ms	remaining: 382ms
226:	learn: 0.0687246	total: 526ms	remaining: 380ms
227:	learn: 0.0684493	total: 528ms	remaining: 377ms
228:	learn: 0.0680584	total: 532ms	remaining: 377ms
229:	learn: 0.0676561	total: 535ms	remaining: 375ms
230:	learn: 0.0672778	total: 539ms	remaining: 373ms
231:	learn: 0.0669345	total: 541ms	remaining: 371ms
232:	learn: 0.0665164	total: 543ms	remaining: 368ms
233:	learn: 0.0661929	total: 547ms	remaining: 367ms
234:	learn: 0.0658258	total: 550ms	remaining: 365ms
235:	learn: 0.0653161	total: 552ms	remaining: 362ms
236:	learn: 0.0648265	total: 554ms	remaining: 360ms
237:	learn: 0.0644266	total: 557ms	remaining: 358ms
238:	learn: 0.0640315	total: 559ms	remaining: 356ms
239:	learn: 0.0638229	total: 563ms	remaining: 354ms
240:	learn: 0.0633837	total: 565ms	remaining: 352ms
241:	learn: 0.0630072	total: 568ms	remaining: 350ms
242:	learn: 0.0627149	total: 570ms	remaining: 347ms
243:	learn: 0.0624566	total: 572ms	remaining: 345ms
244:	learn: 0.0620725	total: 575ms	remaining: 342ms
245:	learn: 0.0615996	total: 577ms	remaining: 340ms
246:	learn: 0.0612885	total: 580ms	remaining: 338ms
247:	learn: 0.0610174	total: 582ms	remaining: 335ms
248:	learn: 0.0604995	total: 584ms	remaining: 333ms
249:	learn: 0.0601394	total: 586ms	remaining: 330ms
250:	learn: 0.0598271	total: 588ms	remaining: 328ms
251:	learn: 0.0595736	total: 590ms	remaining: 325ms
252:	learn: 0.0592283	total: 593ms	remaining: 324ms
253:	learn: 0.0589698	total: 596ms	remaining: 321ms
254:	learn: 0.0587202	total: 598ms	remaining: 319ms
255:	learn: 0.0584382	total: 600ms	remaining: 317ms
256:	learn: 0.0581524	total: 602ms	remaining: 314ms
257:	learn: 0.0578868	total: 604ms	remaining: 311ms
258:	learn: 0.0575921	total: 606ms	remaining: 309ms
259:	learn: 0.0573529	total: 610ms	remaining: 307ms
260:	learn: 0.0570756	total: 612ms	remaining: 305ms
261:	learn: 0.0567464	total: 614ms	remaining: 302ms
262:	learn: 0.0564176	total: 617ms	remaining: 300ms
263:	learn: 0.0560951	total: 619ms	remaining: 298ms
264:	learn: 0.0558022	total: 621ms	remaining: 295ms
265:	learn: 0.0555171	total: 623ms	remaining: 293ms
266:	learn: 0.0552630	total: 626ms	remaining: 291ms
267:	learn: 0.0550169	total: 628ms	remaining: 288ms
268:	learn: 0.0547162	total: 630ms	remaining: 286ms
269:	learn: 0.0543279	total: 632ms	remaining: 283ms
270:	learn: 0.0540038	total: 634ms	remaining: 281ms
271:	learn: 0.0537883	total: 636ms	remaining: 278ms
272:	learn: 0.0535228	total: 639ms	remaining: 276ms
273:	learn: 0.0532815	total: 642ms	remaining: 274ms
274:	learn: 0.0529848	total: 645ms	remaining: 272ms
275:	learn: 0.0526580	total: 647ms	remaining: 270ms
276:	learn: 0.0524286	total: 649ms	remaining: 267ms
277:	learn: 0.0520699	total: 651ms	remaining: 265ms
278:	learn: 0.0518159	total: 653ms	remaining: 262ms
279:	learn: 0.0515380	total: 655ms	remaining: 260ms
280:	learn: 0.0513262	total: 658ms	remaining: 258ms
281:	learn: 0.0510787	total: 660ms	remaining: 255ms
282:	learn: 0.0508852	total: 663ms	remaining: 253ms
283:	learn: 0.0505878	total: 665ms	remaining: 251ms
284:	learn: 0.0502721	total: 667ms	remaining: 248ms
285:	learn: 0.0500015	total: 669ms	remaining: 246ms
286:	learn: 0.0497967	total: 672ms	remaining: 243ms
287:	learn: 0.0495414	total: 674ms	remaining: 241ms
288:	learn: 0.0492732	total: 676ms	remaining: 239ms
289:	learn: 0.0488297	total: 678ms	remaining: 236ms
290:	learn: 0.0485820	total: 680ms	remaining: 234ms
291:	learn: 0.0483652	total: 682ms	remaining: 231ms
292:	learn: 0.0481764	total: 685ms	remaining: 229ms
293:	learn: 0.0479638	total: 687ms	remaining: 227ms
294:	learn: 0.0476034	total: 690ms	remaining: 225ms
295:	learn: 0.0473747	total: 693ms	remaining: 222ms
296:	learn: 0.0471216	total: 695ms	remaining: 220ms
297:	learn: 0.0469196	total: 697ms	remaining: 218ms
298:	learn: 0.0466714	total: 699ms	remaining: 215ms
299:	learn: 0.0464795	total: 702ms	remaining: 213ms
300:	learn: 0.0462706	total: 705ms	remaining: 211ms
301:	learn: 0.0460573	total: 707ms	remaining: 208ms
302:	learn: 0.0458176	total: 710ms	remaining: 206ms
303:	learn: 0.0455819	total: 712ms	remaining: 204ms
304:	learn: 0.0453564	total: 714ms	remaining: 201ms
305:	learn: 0.0451866	total: 716ms	remaining: 199ms
306:	learn: 0.0450249	total: 719ms	remaining: 197ms
307:	learn: 0.0448205	total: 721ms	remaining: 194ms
308:	learn: 0.0445317	total: 723ms	remaining: 192ms
309:	learn: 0.0443438	total: 725ms	remaining: 189ms
310:	learn: 0.0441548	total: 727ms	remaining: 187ms
311:	learn: 0.0439552	total: 729ms	remaining: 185ms
312:	learn: 0.0437932	total: 731ms	remaining: 182ms
313:	learn: 0.0436212	total: 733ms	remaining: 180ms
314:	learn: 0.0433811	total: 736ms	remaining: 178ms
315:	learn: 0.0432205	total: 739ms	remaining: 175ms
316:	learn: 0.0430305	total: 741ms	remaining: 173ms
317:	learn: 0.0428257	total: 743ms	remaining: 171ms
318:	learn: 0.0425618	total: 745ms	remaining: 168ms
319:	learn: 0.0423890	total: 747ms	remaining: 166ms
320:	learn: 0.0422151	total: 750ms	remaining: 163ms
321:	learn: 0.0420329	total: 752ms	remaining: 161ms
322:	learn: 0.0417920	total: 754ms	remaining: 159ms
323:	learn: 0.0416454	total: 757ms	remaining: 156ms
324:	learn: 0.0414150	total: 759ms	remaining: 154ms
325:	learn: 0.0411733	total: 761ms	remaining: 152ms
326:	learn: 0.0410097	total: 763ms	remaining: 149ms
327:	learn: 0.0407865	total: 765ms	remaining: 147ms
328:	learn: 0.0406234	total: 768ms	remaining: 145ms
329:	learn: 0.0403611	total: 770ms	remaining: 142ms
330:	learn: 0.0401662	total: 772ms	remaining: 140ms
331:	learn: 0.0399537	total: 774ms	remaining: 138ms
332:	learn: 0.0398436	total: 776ms	remaining: 135ms
333:	learn: 0.0396280	total: 779ms	remaining: 133ms
334:	learn: 0.0394785	total: 782ms	remaining: 131ms
335:	learn: 0.0393332	total: 784ms	remaining: 128ms
336:	learn: 0.0391744	total: 787ms	remaining: 126ms
337:	learn: 0.0390304	total: 789ms	remaining: 124ms
338:	learn: 0.0388840	total: 791ms	remaining: 121ms
339:	learn: 0.0387088	total: 793ms	remaining: 119ms
340:	learn: 0.0385564	total: 796ms	remaining: 117ms
341:	learn: 0.0384228	total: 799ms	remaining: 115ms
342:	learn: 0.0382276	total: 801ms	remaining: 112ms
343:	learn: 0.0380349	total: 804ms	remaining: 110ms
344:	learn: 0.0378852	total: 806ms	remaining: 107ms
345:	learn: 0.0377292	total: 808ms	remaining: 105ms
346:	learn: 0.0375825	total: 810ms	remaining: 103ms
347:	learn: 0.0374403	total: 813ms	remaining: 100ms
348:	learn: 0.0372495	total: 815ms	remaining: 98.1ms
349:	learn: 0.0371318	total: 817ms	remaining: 95.8ms
350:	learn: 0.0369459	total: 819ms	remaining: 93.4ms
351:	learn: 0.0367446	total: 821ms	remaining: 91ms
352:	learn: 0.0365584	total: 824ms	remaining: 88.7ms
353:	learn: 0.0363792	total: 826ms	remaining: 86.3ms
354:	learn: 0.0362338	total: 829ms	remaining: 84ms
355:	learn: 0.0360570	total: 831ms	remaining: 81.7ms
356:	learn: 0.0359245	total: 834ms	remaining: 79.4ms
357:	learn: 0.0357906	total: 836ms	remaining: 77ms
358:	learn: 0.0356612	total: 838ms	remaining: 74.7ms
359:	learn: 0.0355321	total: 840ms	remaining: 72.3ms
360:	learn: 0.0354118	total: 842ms	remaining: 70ms
361:	learn: 0.0352419	total: 846ms	remaining: 67.8ms
362:	learn: 0.0350788	total: 848ms	remaining: 65.4ms
363:	learn: 0.0349044	total: 850ms	remaining: 63.1ms
364:	learn: 0.0347920	total: 853ms	remaining: 60.7ms
365:	learn: 0.0346406	total: 855ms	remaining: 58.4ms
366:	learn: 0.0344824	total: 857ms	remaining: 56ms
367:	learn: 0.0343241	total: 859ms	remaining: 53.7ms
368:	learn: 0.0342191	total: 861ms	remaining: 51.4ms
369:	learn: 0.0340975	total: 864ms	remaining: 49ms
370:	learn: 0.0339770	total: 866ms	remaining: 46.7ms
371:	learn: 0.0338266	total: 868ms	remaining: 44.3ms
372:	learn: 0.0337375	total: 870ms	remaining: 42ms
373:	learn: 0.0335861	total: 872ms	remaining: 39.6ms
374:	learn: 0.0334720	total: 875ms	remaining: 37.3ms
375:	learn: 0.0333392	total: 878ms	remaining: 35ms
376:	learn: 0.0332263	total: 881ms	remaining: 32.7ms
377:	learn: 0.0330819	total: 883ms	remaining: 30.4ms
378:	learn: 0.0329381	total: 885ms	remaining: 28ms
379:	learn: 0.0328072	total: 887ms	remaining: 25.7ms
380:	learn: 0.0326902	total: 889ms	remaining: 23.3ms
381:	learn: 0.0325702	total: 891ms	remaining: 21ms
382:	learn: 0.0324447	total: 894ms	remaining: 18.7ms
383:	learn: 0.0323468	total: 896ms	remaining: 16.3ms
384:	learn: 0.0321881	total: 899ms	remaining: 14ms

In [16]:
print(best_params, final_threshold)

OrderedDict({'depth': 6, 'iterations': 391, 'l2_leaf_reg': 8.462943990782671, 'learning_rate': 0.02069186296126172}) 0.671511316428229

### Final Model Sample Prediction

In [17]:
def test_final_model(model, threshold):
    test_size = 189
    Xnew = X.iloc[:test_size].values
    ypred, ypredproba = hpo.model_predict(Xnew, model, threshold)
    ynew=y.iloc[:test_size].values

    cm = confusion_matrix(ynew, ypred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else np.nan
    specificity = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    youden_test = (
        sensitivity + specificity - 1
        if not (np.isnan(sensitivity) or np.isnan(specificity))
        else np.nan
    )
    roc_auc = (
        roc_auc_score(ypred, ypredproba)
        if len(np.unique(ynew)) > 1
        else np.nan
    )

    print(youden_test, roc_auc)

test_final_model(final_model, final_threshold)

1.0 1.0

 -----

### Save artifacts and metrics

In [18]:
outputdir = config_path /  config.experiment.tag / config.experiment.stage
outputdir.mkdir(parents=True, exist_ok=True)
print(outputdir)

experiments\binary\development\hyperparameter_optimization

In [19]:
final_model_dict = {
    'name': config.model.name,
    'model': final_model,
    'best_params': best_params,
    'threshold' : final_threshold
}

In [20]:
joblib.dump(opt_results, outputdir / "optimization_results.joblib");
joblib.dump(final_model_dict, outputdir / "final_model_dict.joblib");
opt_results_df.to_csv(outputdir / "optimization_results_summary.csv")

### Load Save Results and Verify

In [21]:
loaded_optimization_results = joblib.load(outputdir / "optimization_results.joblib")
loaded_optimization_results

{'roc_auc_mean': 0.9692212825933756,
 'roc_auc_std': 0.018776054590824542,
 'youden_mean': 0.7956483439041578,
 'youden_std': 0.08021401914153416,
 'sensitivity_mean': 0.9039816772374912,
 'specificity_mean': 0.8916666666666666,
 'threshold_mean': 0.6488591221384802,
 'threshold_std': 0.14354802298703395,
 'folds': [{'fold': 0,
   'roc_auc': 0.9840909090909091,
   'youden': 0.9090909090909092,
   'sensitivity': 0.9090909090909091,
   'specificity': 1.0,
   'threshold': 0.7137815889585889,
   'best_params': {'iterations': 433,
    'depth': 5,
    'learning_rate': 0.015199348301309814,
    'l2_leaf_reg': 2}},
  {'fold': 1,
   'roc_auc': 0.9755813953488373,
   'youden': 0.6499999999999999,
   'sensitivity': 1.0,
   'specificity': 0.65,
   'threshold': 0.3794176963815851,
   'best_params': {'iterations': 231,
    'depth': 10,
    'learning_rate': 0.04635431984752397,
    'l2_leaf_reg': 5}},
  {'fold': 2,
   'roc_auc': 0.9348837209302325,
   'youden': 0.8069767441860465,
   'sensitivity': 0.9069767441860465,
   'specificity': 0.9,
   'threshold': 0.6339991006349044,
   'best_params': {'iterations': 244,
    'depth': 8,
    'learning_rate': 0.024761648314181258,
    'l2_leaf_reg': 4}},
  {'fold': 3,
   'roc_auc': 0.9568181818181818,
   'youden': 0.7636363636363637,
   'sensitivity': 0.8636363636363636,
   'specificity': 0.9,
   'threshold': 0.7714033672672544,
   'best_params': {'iterations': 496,
    'depth': 7,
    'learning_rate': 0.019118213268168986,
    'l2_leaf_reg': 1}},
  {'fold': 4,
   'roc_auc': 0.9720930232558139,
   'youden': 0.8534883720930233,
   'sensitivity': 0.9534883720930233,
   'specificity': 0.9,
   'threshold': 0.5813105345007075,
   'best_params': {'iterations': 141,
    'depth': 9,
    'learning_rate': 0.024821724395582237,
    'l2_leaf_reg': 6}},
  {'fold': 5,
   'roc_auc': 0.991860465116279,
   'youden': 0.7906976744186047,
   'sensitivity': 0.7906976744186046,
   'specificity': 1.0,
   'threshold': 0.8132424450878413,
   'best_params': {'iterations': 383,
    'depth': 9,
    'learning_rate': 0.044214208459664416,
    'l2_leaf_reg': 4}}]}

In [22]:
loaded_final_model_dict = joblib.load(outputdir / "final_model_dict.joblib")
loaded_final_model_dict

{'name': 'catboost',
 'model': <catboost.core.CatBoostClassifier at 0x217676dc290>,
 'best_params': OrderedDict([('depth', 6),
              ('iterations', 391),
              ('l2_leaf_reg', 8.462943990782671),
              ('learning_rate', 0.02069186296126172)]),
 'threshold': 0.671511316428229}

In [23]:
test_final_model(
    loaded_final_model_dict["model"], 
    loaded_final_model_dict["threshold"])

1.0 1.0

In [24]:
pd.read_csv(outputdir / "optimization_results_summary.csv")

         Unnamed: 0           value
0            youden  0.796 +/ 0.080
1         youden ci   0.725 - 0.866
2           roc_auc  0.969 +/ 0.019
3        roc_auc ci   0.953 - 0.986
4         threshold  0.649 +/ 0.144
5  specificity mean           0.892
6  sensitivity mean           0.904