# Feature and Model Selection

In [15]:
import warnings
import joblib
from pathlib import Path
import shutil

import numpy as np
import pandas as pd


import sys 
sys.path.append('..')  

from module.dataload import DPN_data
import ymlconfig

%matplotlib inline
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')
np.set_printoptions(precision=3)  # decimal places for outputs from numpy
pd.set_option("display.precision", 3)  # decimal places for outputs from pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Load / Reload Selection Utility Functions

In [16]:
from utils2 import selection as sel

----

## Read Config File

In [17]:
config_path = Path(r'experiments')

# choose between final and development config file
# config_filename = "bin_sel_dev.yml" # development
config_filename = "bin_sel_final_202608.yml" # final

config_dict = ymlconfig.load_config(config_path / config_filename)
config = ymlconfig.dict_to_namespace(config_dict)
config_dict

{'experiment': {'summary': 'binary classification - feature  and model selection (final experiment) after code review using dataset for public request',
  'classification_type': 'binary',
  'stage': 'selection',
  'tag': 'final_202608',
  'verbosity': 0,
  'random_seed': 42},
 'data': {'dataset_path': '../dataset/EAMC_DPN_Dataset.xlsx'},
 'feature_selection': {'cross_validation': {'k_splits': 4,
   'n_repeats': 10,
   'sort_by': 'auprc'},
  'vif_threshold': 5},
 'figures': {'summary_table_topk': 5}}

#### Set output directory

In [18]:
outputdir = config_path /  config.experiment.classification_type /  config.experiment.stage / config.experiment.tag 
outputdir.mkdir(parents=True, exist_ok=True)
print(outputdir)

experiments/binary/selection/final_202608

#### Copy config file to output directory

In [19]:
source = config_path / config_filename
destination = outputdir / config_filename
shutil.copy(source, destination)

PosixPath('experiments/binary/selection/final_202608/bin_sel_final_202608.yml')

## Data Loading

In [20]:
D = DPN_data(config.data.dataset_path)
D.load(classification=config.experiment.classification_type);
D.df.tail(3)

Data laoding cleaning report written to ../dataset/cleaning_report.txt.

,SEX,AGE,SUBJ,DM_DUR,INSULIN,HBA1C,HPN,PAOD,DSLPDMIA,CKD,GBS,DEC_VS,DEC_PPS,DEC_LTS,DEC_AR,MNSI,SSA_L,SSC_L,SPSA_L,SPSC_L,MCV_L,DL_L,CMAPANK_L,CMAPKNE_L,FWAVE_L,SSA_R,SSC_R,SPSA_R,SPSC_R,MCV_R,DL_R,CMAPANK_R,CMAPKNE_R,FWAVE_R,FEET_MEAN_ESC,FEET_PCT_ASYM,HAND_MEAN_ESC,HAND_PCT_ASYM,NS,CAS,Confirmed_Binary_DPN
184,1,36,0,1.0,1,6.18,1,0,0,1,0,0,1,0,1,3,11.45,49.2,13.79,40.2,41.8,3.60,11.94,8.78,50.3,14.11,43.1,14.95,41.2,42.2,3.7,9.43,7.19,49.9,69,4,56,8,83.0,7.0,0
185,0,60,1,5.0,1,12.20,1,0,1,0,0,1,1,1,1,8,5.03,37.9,0.00,0.0,36.3,4.85,5.05,3.06,53.1,5.58,37.2,0.00,0.0,32.2,4.2,5.09,3.28,53.5,16,11,21,9,46.0,32.0,1
186,0,65,1,15.0,1,7.59,1,1,0,1,0,1,1,1,1,8,0.00,0.0,0.00,0.0,43.2,5.80,0.56,0.20,0.0,0.00,0.0,0.00,0.0,48.1,5.7,0.27,0.11,0.0,39,16,41,23,43.0,44.0,1

Binary Classification Classes:  ['Negative', 'Possible', 'Probable'] vs 'Confirmed'

In [21]:
dfdpn = D.df
data_cols = dfdpn.drop(D.non_data_cols, axis=1, errors="ignore").columns
len(data_cols), data_cols

(40,
 Index(['SEX', 'AGE', 'SUBJ', 'DM_DUR', 'INSULIN', 'HBA1C', 'HPN', 'PAOD',
        'DSLPDMIA', 'CKD', 'GBS', 'DEC_VS', 'DEC_PPS', 'DEC_LTS', 'DEC_AR',
        'MNSI', 'SSA_L', 'SSC_L', 'SPSA_L', 'SPSC_L', 'MCV_L', 'DL_L',
        'CMAPANK_L', 'CMAPKNE_L', 'FWAVE_L', 'SSA_R', 'SSC_R', 'SPSA_R',
        'SPSC_R', 'MCV_R', 'DL_R', 'CMAPANK_R', 'CMAPKNE_R', 'FWAVE_R',
        'FEET_MEAN_ESC', 'FEET_PCT_ASYM', 'HAND_MEAN_ESC', 'HAND_PCT_ASYM',
        'NS', 'CAS'],
       dtype='object'))

### Data Inspection

In [22]:
X = dfdpn[data_cols]
y = dfdpn['Confirmed_Binary_DPN']
X.shape, y.shape

((187, 40), (187,))

In [23]:
# get number of postive and negative class
print('Confirmed - positive class', y.sum())
print('Non-confirmed - negative class', y.shape[0]-y.sum())

Confirmed - positive class 130
Non-confirmed - negative class 57

In [24]:
D.classification_df

   Confirmed  Probable  Possible  Any_DPN  Negative
0        130        27        22      179         8

----

## Global Variables

In [27]:
model_metrics = {} # key: experiment code, value: {model: <string> (e.g. all, ncs), rcv_cores: <Dataframe> Perfomance metrics of repeated k-fold of algorithms}
metrics_stats = {} # key: experiment code, value: {stat: <string> (e.g. mean, std), stat (mean/std) of the performance of all algorithms}
youden_scores = {} # key: experiment code, value: list of youden cv scores algorithms
rocauc_scores = {} # key: experiment code, value: list of roc-auc cv scores algorithms

## Iterative Group Feature Elimination

----

### All Features

In [28]:
model_metrics['All'] = sel.benchmark_models(X, y, config)

TypeError: benchmark_models() missing 2 required positional arguments: 'include_cols' and 'config'

In [ ]:
model_metrics['All'] # list of dictionary with 2 keys, model and scores (a dataframe)

In [ ]:
model_metrics.keys() # only experiment named 'All'  loaded so far

In [ ]:
len(model_metrics['All']) # number of algorithms

In [ ]:
model_metrics['All'][0]['model'] # Get model name of algo 0

In [ ]:
# get scores for algo 1 (Logistic Regression)   
# expect k*N_REPEATS rows (e.g. 10 for k=5, NREPEATS=2)

model_metrics['All'][1]['rcv_scores']

In [ ]:
metrics_stats['All'] = sel.calculate_metric_statistics(model_metrics['All'], config)

In [ ]:
metrics_stats['All']['std']

#### Get youden and roc-auc scores

In [ ]:
youden_scores['All'] = sel.get_metric_scores(model_metrics, 'All', metrics_stats, 'youden')
rocauc_scores['All'] = sel.get_metric_scores(model_metrics, 'All', metrics_stats, 'roc-auc')
rocauc_scores['All']

In [ ]:
sel.plot_metric_scores(youden_scores, config, exp_code='All', savedir=outputdir)

In [ ]:
sel.plot_metric_scores(rocauc_scores, config, exp_code='All', 
                       target_metric='roc-auc',savedir=outputdir)

### No Collinear Features

In [ ]:
high_vif = sel.get_high_vif(X, config)

In [ ]:
# drop these features which seem to be collinear
high_vif_features = high_vif.feature.values.tolist()[1:]
print(high_vif_features)

In [ ]:
Xnc = X.drop(columns=high_vif_features) #X no collinear
print(Xnc.shape) 
Xnc.head(2)

In [ ]:
model_metrics['NoCol'] = sel.benchmark_models(Xnc, y, config, verbosity=0)
metrics_stats['NoCol'] = sel.calculate_metric_statistics(model_metrics['NoCol'], config)
metrics_stats['NoCol']['mean']

 -----

### No NCS

In [ ]:
Xnncs = X.drop(columns=D.ncs_cols) #X no nerve conduction studies
print(D.ncs_cols)
Xnncs.shape, Xnncs.head(2)

In [ ]:
model_metrics['NoNCS'] = sel.benchmark_models(Xnncs, y, config, verbosity=0)
metrics_stats['NoNCS'] = sel.calculate_metric_statistics(model_metrics['NoNCS'], config)
metrics_stats['NoNCS']['mean']

 -----

### No Sudoscan Features

In [ ]:
Xnsudo = X.drop(columns=D.sudo_cols) #X no nerve conduction studies
print(D.sudo_cols)
print(Xnsudo.shape)
Xnsudo.head(2)

In [ ]:
model_metrics['NoSudo'] = sel.benchmark_models(Xnsudo, y, config, verbosity=0)
metrics_stats['NoSudo'] = sel.calculate_metric_statistics(model_metrics['NoSudo'], config)
metrics_stats['NoSudo']['mean']

 -----

### No Neuro Features

In [ ]:
Xnneuro = X.drop(columns=D.neuro_cols) #X no neuro columns
print(D.neuro_cols)
print(Xnneuro.shape) 
Xnneuro.head(2)

In [ ]:
model_metrics['NoNeuro'] = sel.benchmark_models(Xnneuro, y, config,verbosity=0)
metrics_stats['NoNeuro'] = sel.calculate_metric_statistics(model_metrics['NoNeuro'], config)
metrics_stats['NoNeuro']['mean']

 -----

### No Commorbidity Features

In [ ]:
Xncom = X.drop(columns=D.comorbidity_cols) #X no neuro columns
print(D.comorbidity_cols)
print(Xncom.shape)
Xncom.head(2)

In [ ]:
model_metrics['NoCom'] = sel.benchmark_models(Xncom, y, config, verbosity=0)
metrics_stats['NoCom'] = sel.calculate_metric_statistics(model_metrics['NoCom'], config)
metrics_stats['NoCom']['mean']

 -----

### No MNSI Feature

In [ ]:
Xnmnsi = X.drop(columns=D.mnsi_col) #X no neuro columns
print(D.mnsi_col)
print(Xnmnsi.shape)
Xnmnsi.head(2)

In [ ]:
model_metrics['NoMSI'] = sel.benchmark_models(Xnmnsi, y, config, verbosity=0)
metrics_stats['NoMSI'] = sel.calculate_metric_statistics(model_metrics['NoMSI'], config)
metrics_stats['NoMSI']['mean']

 -----

### No Profile Feature

In [ ]:
Xnprof = X.drop(columns=D.profile_cols) #X no neuro columns
print(D.profile_cols)
print(Xnprof.shape) 
Xnprof.head(2)

In [ ]:
model_metrics['NoProf'] = sel.benchmark_models(Xnprof, y, config, verbosity=0)
metrics_stats['NoProf'] = sel.calculate_metric_statistics(model_metrics['NoProf'], config)
metrics_stats['NoProf']['mean']

 -----

### NCS Only

In [ ]:
Xncs = X[D.ncs_cols] #X nerve conduction studies
print(D.ncs_cols)
print(Xncs.shape) 
Xncs.head(2)

In [ ]:
model_metrics['NCS'] = sel.benchmark_models(Xncs, y, config, verbosity=0)
metrics_stats['NCS'] = sel.calculate_metric_statistics(model_metrics['NCS'], config)
metrics_stats['NCS']['mean']

### Sudoscan Only Only

In [ ]:
Xsudo = X[D.sudo_cols] 
print(Xsudo.shape) 
Xsudo.head(2)

In [ ]:
model_metrics['Sudo'] = sel.benchmark_models(Xsudo, y, config, verbosity=0)
metrics_stats['Sudo'] = sel.calculate_metric_statistics(model_metrics['Sudo'], config)
metrics_stats['Sudo']['mean']

## Summary of Iterative Group Feature Elimination

In [ ]:
model_metrics.keys(), metrics_stats.keys()

In [ ]:
summary_metric = config.figures.summary_metric
summary_topk = config.figures.summary_table_topk

In [ ]:
from utils2 import selection as sel

In [ ]:
# Summary: including all columns and stats
sel.create_model_summary_table(metrics_stats, config,
                           exclude_features=[],
                           include_mean=True, 
                           show_plot=True,
                           savedir=outputdir);

In [ ]:
# Summary: clean table without mean, topk
sel.create_model_summary_table(metrics_stats, config,
                           topk=0, 
                           exclude_features=[],
                           include_mean=False, 
                           show_plot=False,
                           savedir=outputdir);

In [ ]:
# ROC-AUC Summary: including all columns and stats
sel.create_model_summary_table(metrics_stats, config, 
                           target_metric='roc-auc', 
                           exclude_features=[],
                           include_mean=True, 
                           show_plot=True,
                           savedir=outputdir);

In [ ]:
# ROC-AUC Summary: clean table without mean, topk
sel.create_model_summary_table(metrics_stats, config,
                           target_metric='roc-auc', 
                           topk=0, 
                           exclude_features=[],
                           include_mean=False, 
                           show_plot=False,
                           savedir=outputdir);

 -----

## Save the Metrics to json

In [ ]:
joblib.dump(model_metrics, outputdir / "model_metrics.joblib");
joblib.dump(metrics_stats, outputdir / "metrics_stats.joblib");
joblib.dump(youden_scores, outputdir / "youden_scores.joblib");
joblib.dump(rocauc_scores, outputdir / "rocauc_scores.joblib");

 -----

## Load Save Results and Verify

In [ ]:
# Verify saved results
loaded_model_metrics = joblib.load(outputdir / "model_metrics.joblib")
sel.calculate_metric_statistics(loaded_model_metrics['All'], config)

In [ ]:
loaded_metric_stats = joblib.load(outputdir / "metrics_stats.joblib")
loaded_metric_stats['NoNCS']['mean']

In [ ]:
loaded_youden_scores = joblib.load(outputdir / "youden_scores.joblib")
sel.plot_metric_scores(loaded_youden_scores, 
                       config, exp_code='All', 
                       sorted=True, 
                       savedir=None)

In [ ]:
loaded_rocauc_scores = joblib.load(outputdir / "rocauc_scores.joblib")
sel.plot_metric_scores(loaded_rocauc_scores, config, exp_code='All', sorted=True, 
                   target_metric='roc-auc',
                   savedir=None)

 -----